Repository checkmate2022/Backend, pull requests merged in 2022-05, with the labels that each got.

#3 feat : rest api, exception 처리
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  build.gradle
  src/main/java/com/checkmate/backend/advice/ExceptionAdvice.java
  src/main/java/com/checkmate/backend/advice/exception/LoginFailedException.java
  src/main/java/com/checkmate/backend/common/CommonResult.java
  src/main/java/com/checkmate/backend/common/ListResult.java
  src/main/java/com/checkmate/backend/common/SingleResult.java
  src/main/java/com/checkmate/backend/config/Swagger2Config.java
  src/main/java/com/checkmate/backend/service/ResponseService.java
  src/main/resources/application.yml
Labels: status : 완료👍, status : 리뷰요청

#9 Feature/login 닉네임 ID 중복확인
  build.gradle
  src/main/java/com/checkmate/backend/oauth/api/controller/UserController.java
  src/main/java/com/checkmate/backend/oauth/api/entity/User.java
  src/main/java/com/checkmate/backend/oauth/api/repo/UserRepository.java
  src/main/java/com/checkmate/backend/oauth/config/SecurityConfig.java
  src/main/java/com/checkmate/backend/oauth/service/CustomUserDetailService.java
  src/main/java/com/checkmate/backend/oauth/service/UserService.java
Labels: status : 리뷰요청

#8 Schedule API, Avatar API
  build.gradle
  src/main/java/com/checkmate/backend/oauth/api/controller/AvatarController.java
  src/main/java/com/checkmate/backend/oauth/api/controller/ScheduleController.java
  src/main/java/com/checkmate/backend/oauth/api/entity/Avatar.java
  src/main/java/com/checkmate/backend/oauth/api/entity/AvatarImage.java
  src/main/java/com/checkmate/backend/oauth/api/entity/Participant.java
  src/main/java/com/checkmate/backend/oauth/api/entity/Schedule.java
  src/main/java/com/checkmate/backend/oauth/api/entity/User.java
  src/main/java/com/checkmate/backend/oauth/api/repo/AvatarRepository.java
  src/main/java/com/checkmate/backend/oauth/api/repo/FileRepository.java
  src/main/java/com/checkmate/backend/oauth/api/repo/ParticipantRepository.java
  src/main/java/com/checkmate/backend/oauth/api/repo/ScheduleRepository.java
  src/main/java/com/checkmate/backend/oauth/api/repo/UserRepository.java
  src/main/java/com/checkmate/backend/oauth/model/ScheduleDto.java
  src/main/java/com/checkmate/backend/oauth/model/ScheduleRequest.java
  src/main/java/com/checkmate/backend/oauth/model/ScheduleResponse.java
  src/main/java/com/checkmate/backend/oauth/model/UserDto.java
  src/main/java/com/checkmate/backend/oauth/service/AvatarService.java
  src/main/java/com/checkmate/backend/oauth/service/FileService.java
  src/main/java/com/checkmate/backend/oauth/service/ScheduleService.java
  src/main/resources/application.yml
Labels: status : 완료👍
